2.1 New
Sevan16/TKI-142- pull request #13
Opened 2023-12-04 07:20 UTC by Sevan16

2023-12-04 19:59 UTC, BalakinaEP requested changes

2023-12-04 19:59 UTC, BalakinaEP commented on main.c
> +int get_value();
Документация

2023-12-04 19:59 UTC, BalakinaEP commented on main.c
> +       printf("Please input only 1 or 2");
`return 1;`

2023-12-12 10:25 UTC, Sevan16 commented on main.c
> +       printf("Please input only 1 or 2");
[Uploading Задание 4-1  (2).docx…]()

2023-12-21 20:13 UTC, closed without merging